server:
    port: 8081
spring:
    datasource:
        password: Satya@007
        url: jdbc:mysql://localhost:3306/users?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        username: root
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
